trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - src/*
      - test/*
      - package.json
      - tsconfig.json
      - jest.config.js

pr:
  branches:
    include:
      - main
  paths:
    include:
      - src/*
      - test/*
      - package.json
      - tsconfig.json
      - jest.config.js

pool: Default # Self-hosted agent pool

steps:
  - checkout: self
    displayName: 'Checkout repository'

  - script: |
      docker build -t typescript-dev .
    displayName: 'Build Docker image'

  - script: |
      docker run --rm -v $(Build.SourcesDirectory)/:/app typescript-dev npm install
    displayName: 'Install dependencies'

  - script: |
      docker run --rm -v $(Build.SourcesDirectory)/:/app typescript-dev npx tsc --noEmit
    displayName: 'TypeScript type checking'

  - script: |
      docker run --rm -v $(Build.SourcesDirectory)/:/app typescript-dev npx jest
    displayName: 'Run Jest tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
    displayName: 'Publish test results'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dist'
      artifactName: 'dist'
      publishLocation: 'Container'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: 'Publish build artifacts'