# Azure Pipelines configuration for TypeScript project
trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - src/*
      - test/*
      - package.json
      - tsconfig.json
      - jest.config.js

pr:
  branches:
    include:
      - main
  paths:
    include:
      - src/*
      - test/*
      - package.json
      - tsconfig.json
      - jest.config.js

pool:
  vmImage: 'ubuntu-latest' # Azure-hosted agent (can be changed to self-hosted)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x' # Node.js version (matches your GitHub Actions workflow)
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm install --save-dev typescript jest ts-jest @types/jest
    displayName: 'Install TypeScript and Jest'

  - script: |
      npx tsc --noEmit
    displayName: 'TypeScript type checking'

  - script: |
      npx jest
    displayName: 'Run Jest tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
    displayName: 'Publish test results'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dist'
      artifactName: 'dist'
      publishLocation: 'Container'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: 'Publish build artifacts'
